# Generated by Django 3.1.6 on 2021-02-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbacksByTelegramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FilesByTelegramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileTelegramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.TextField(verbose_name='User id in telegrams')),
                ('current_count_of_completed_projects', models.TextField(blank=True, default=None, null=True, verbose_name='Current number of user projects completed')),
                ('current_count_of_active_projects', models.TextField(blank=True, default=None, null=True, verbose_name='Current number of user projects active')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsByTelegramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.TextField(verbose_name='User id in telegrams')),
                ('title', models.TextField(verbose_name='Title of project')),
                ('img', models.TextField(verbose_name='Attached files')),
                ('data_of_create', models.DateField(auto_now_add=True, verbose_name='Date of create project')),
                ('cost', models.TextField(verbose_name='Project cost')),
                ('category', models.TextField(verbose_name='Category name')),
                ('description', models.TextField(verbose_name='Project description')),
                ('status', models.TextField(verbose_name='Status of project')),
                ('performer_ext_id', models.TextField(verbose_name='Id telegram user which perform task')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.TextField(verbose_name='User id in telegrams')),
                ('current_lang', models.TextField(verbose_name='Telegram user selected language')),
                ('username', models.TextField(verbose_name='Username in telegrams')),
                ('fullname', models.TextField(blank=True, default=None, max_length=128, null=True, verbose_name='fullname')),
                ('rights', models.TextField(verbose_name='Telegram bot user rights')),
                ('date_of_creation', models.DateField(auto_now_add=True, verbose_name='Date of creation user')),
                ('date_of_when_began_admin', models.DateField(auto_now=True, verbose_name='Date of when began admin')),
                ('email', models.EmailField(blank=True, default=None, max_length=64, null=True, verbose_name='User email')),
            ],
        ),
        migrations.CreateModel(
            name='UserRequestTopOfBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.TextField(verbose_name='User id in telegrams')),
                ('sum', models.TextField(verbose_name='Top-up amount')),
            ],
        ),
        migrations.CreateModel(
            name='UserRequestWithdrawCash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.TextField(verbose_name='User id in telegrams')),
                ('sum', models.TextField(blank=True, default=None, null=True, verbose_name='Top-up amount')),
                ('bank_name', models.TextField(blank=True, default=None, null=True, verbose_name='User bank card')),
                ('card_num', models.TextField(blank=True, default=None, null=True, verbose_name='User bank card')),
                ('phone_num', models.TextField(blank=True, default=None, null=True, verbose_name='User phone')),
            ],
        ),
    ]
